services:
  nihongo-master-prod:
    image: node:22-slim
    container_name: nihongo-master-prod
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build && npx vite preview --host 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production

  nihongo-master-test:
    image: node:22-slim
    container_name: nihongo-master-test
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npx vite --host 0.0.0.0 --port 3001"
    ports:
      - "3001:3001"
    restart: always
    environment:
      - NODE_ENV=development
